---
  - name: stop bamboo service
    service:
      name: bamboo
      enabled: yes
      state: stopped
    ignore_errors: yes

  - name: kill bamboo
    command: "pkill -9 -U {{bamboo_user}}"
    ignore_errors: yes

  - name: create user to run bamboo
    user: name={{bamboo_user}}

  - name: Add EPEL repository
    yum:
      name: http://dl.fedoraproject.org/pub/epel/7/x86_64/e/epel-release-7-9.noarch.rpm
      state: present

  - name: install useful packages
    yum:
      name: wget,elinks,telnet,htop,mlocate,python-pip,vim,nano,jq,java-1.8.0-openjdk-devel,unzip,maven,libunwind,libicu

  - name: download .NET Core
    get_url:
          url: "{{dot_net_download}}"
          dest: /tmp/dotnet.tar.gz
          mode: 0440

  - name: create dotnet directory
    file:
        path: /opt/dotnet
        state: directory

  - name: extract dotnet
    unarchive:
        src: /tmp/dotnet.tar.gz
        dest: /opt/dotnet
        copy: no

  - name: link dotnet
    file:
      src: /opt/dotnet/dotnet
      dest: /usr/local/bin/dotnet
      state: link

  - name: install mono key
    get_url:
        url: http://keyserver.ubuntu.com/pks/lookup?op=get&search=0x3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF
        dest: /tmp/GPG-KEY-mono
        mode: 0440

  - name: import mono key
    rpm_key:
      state: present
      key: /tmp/GPG-KEY-mono

  - name: Add mono repo
    yum_repository:
      name: mono
      description: Mono repository
      baseurl: http://download.mono-project.com/repo/centos7/
      gpgkey: http://keyserver.ubuntu.com/pks/lookup?op=get&search=0x3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF
      gpgcheck: yes
      enabled: yes

  - name: install mono
    yum:
      name: mono-devel

  - name: Set JAVA_HOME
    lineinfile: dest=/etc/environment state=present regexp='^JAVA_HOME' line='JAVA_HOME=/usr/lib/jvm/jre-1.8.0'

  - name: download bamboo
    get_url:
        url: "{{bamboo_download}}"
        dest: /tmp/bamboo.tar.gz
        mode: 0440

  - name: download bamboo
    get_url:
        url: "{{bamboo_cli_download}}"
        dest: /tmp/atlassian-cli.zip
        mode: 0440

  - name: extract bamboo
    unarchive:
        src: /tmp/bamboo.tar.gz
        dest: /opt
        copy: no

  - name: download octopus cli
    get_url:
        url: "{{octopus_cli_download}}"
        dest: /tmp/octopus-tools.tar.gz
        mode: 0440

  - name: create octopus cli directory
    file:
        path: /opt/octocli
        state: directory

  - name: extract octopus cli
    unarchive:
        src: /tmp/octopus-tools.tar.gz
        dest: /opt/octocli
        copy: no

  - name: create plugins directory
    file:
        path: /opt/atlassian-bamboo-6.0.0/plugins
        state: directory

  - name: extract bamboo
    unarchive:
        src: /tmp/atlassian-cli.zip
        dest: /opt
        copy: no

  - name: set bamboo permissions
    file:
      state: directory
      path: /opt/atlassian-bamboo-6.0.0
      owner: "{{bamboo_user}}"
      group: "{{bamboo_user}}"
      recurse: true

  - name: Fix up bamboo home
    lineinfile:
      dest: /opt/atlassian-bamboo-6.0.0/atlassian-bamboo/WEB-INF/classes/bamboo-init.properties
      state: present
      regexp: '^bamboo.home'
      line: 'bamboo.home=/opt/atlassian-bamboo-6.0.0'

  - name: install bamboo service
    template:
      src: bamboo
      dest: /etc/init.d/bamboo
      owner: root
      group: root
      mode: 0755

  - name: copy plugin
    copy:
        src: "/mnt/c/Users/matth/Octopus/OctopusBamboo/target/OctopusBamboo-1.0.0-SNAPSHOT.jar"
        dest: "/opt/atlassian-bamboo-6.0.0/plugins/OctopusBamboo-1.0.0-SNAPSHOT.jar"
        owner: "{{bamboo_user}}"
        group: "{{bamboo_user}}"
        mode: 0644

  - name: start bamboo service
    service:
      name: bamboo
      enabled: yes
      state: restarted